### ISSUE TITLE
Add/design slack and Github

### ISSUE THREAD

**Issue by TeAmP0is0N** [osDFS/osDFS-V2#24]
Follow the below screenshots
![Screenshot (217)](https://user-images.githubusercontent.com/42641738/86535054-2bda0a80-befb-11ea-9f49-40c4a1e01c23.png)

**Comment by ArpitFalcon** [comment]
Can you assign me this issue, Please?

**Comment by TeAmP0is0N** [comment]
@ArpitFalcon Go ahead.

**Comment by TeAmP0is0N** [comment]
@ArpitFalcon Are you working on it?
