### ISSUE TITLE
Adding Preloader to all the pages

### ISSUE THREAD

**Issue by soumyajit4419** [osDFS/osDFS-V2#31]
Presently the preloader is only in Index.html page.
It can be added to all the pages present.

**Comment by TeAmP0is0N** [comment]
but why all pages?

**Comment by TeAmP0is0N** [comment]
because our main page will open firstly. And when the main page will open then the whole site will be loaded completely.

**Comment by soumyajit4419** [comment]
No site this is not single page. Each part is an individual page.So each page loads when it it clicked.
So its good to add an preloader to all pages.

**Comment by TeAmP0is0N** [comment]
ok good idea. Will do.
